services:
  backend:
    build: .
    ports:
      - "10000:10000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"